name: Keep-alive

on:
  # remove this before merging
  pull_request:
  schedule:
    # Runs every sunday at 3 a.m.
    - cron: '0 3 * * SUN'

jobs:
  # uncommmment this before merging
  # call-test-workflow:
  #   uses: BlueBrain/BluePyEfe/.github/workflows/test.yml@master
  
  keep-workflow-alive:
    name: Keep workflow alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Set flag if last commit is more than 50 days old
        env:
          COMMIT_DATE: ${{ github.event.head_commit.message }}
        run: |
          echo ${{ github.event.created_at }}
          echo ${{ github.event.base.repo.updated_at }}

          echo ${{ github.event.created_at }} - ${{ github.event.base.updated_at }}

          # condition=`date -d "-50 days"`
          # echo "${COMMIT_DATE}"
          # echo $condition
          # if [ ${COMMIT_DATE} -le $condition ];
          # then
          #   echo "flag=true" >> $GITHUB_ENV
          #   echo "flag set to true"
          # else
          #   echo "flag=false" >> $GITHUB_ENV
          #   echo "flag set to false"
          # fi

      - name: setup git config
        if: env.flag
        run: |
          # setup the username and email.
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        if: env.flag
        run: |
          git commit -m "Empty commit to keep the gihub workflows alive" --allow-empty
          git push origin master
